/* post table */
CREATE TABLE POST(
 POSTNO NUMBER PRIMARY KEY,
 EMAIL VARCHAR2(1000),
 PLAN VARCHAR2(1000),
 TITLEIMAGE VARCHAR2(1000),
 IMAGES VARCHAR2(1000),
 CONTENT VARCHAR2(1000),
 HASHTAG VARCHAR2(1000),
 REGDATE DATE DEFAULT sysdate,
 VIEWS NUMBER DEFAULT 0,
 AUTHORITY VARCHAR2(1000)
);
CREATE SEQUENCE POST_NO_SEQ NOCACHE;
 
/* post_like table */
CREATE TABLE POST_LIKE(
 POSTLIKENO number PRIMARY KEY,
 POSTNO NUMBER,
 EMAIL VARCHAR2(1000),
 LIKES NUMBER DEFAULT 0
);

CREATE SEQUENCE POST_LIKE_SEQ NOCACHE;

/* post_comments table */
CREATE TABLE COMMENTS (
 COMMENTNO NUMBER PRIMARY KEY,
 POSTNO NUMBER,
 EMAIL  VARCHAR2(100),
 CONTENT VARCHAR2(1000),
 TIME DATE DEFAULT sysdate,
 grp number DEFAULT 0,
 grpl number DEFAULT 0,
 grps number DEFAULT 0
);
CREATE SEQUENCE COMMENTS_SEQ NOCACHE;

CREATE TABLE POST_VIEW(
 POSTVIEWNO number PRIMARY KEY,
 POSTNO NUMBER,
 EMAIL VARCHAR2(1000),
 VIEWS NUMBER DEFAULT 0
);

CREATE SEQUENCE post_view_seq NOCACHE;

CREATE TABLE post_dt (
 postNo NUMBER NOT NULL,
 planNum NUMBER NOT NULL,
 planDtNum NUMBER NOT NULL,
 location VARCHAR2(1000) NOT NULL
);


/* ÀÛ¾÷¿ë */

DROP SEQUENCE post_view_seq;
DROP SEQUENCE post_no_SEQ;
DROP SEQUENCE COMMENTS_SEQ;
DROP SEQUENCE POST_LIKE_SEQ;
DROP TABLE post_view_seq;
DROP TABLE POST;
DROP TABLE POST_LIKE;
DROP TABLE COMMENTS;
DROP TABLE POST_VIEW;
DROP TABLE post_dt;

SELECT * FROM COMMENTS;

SELECT COUNT(COMMENTNO) comments 
FROM POST a, COMMENTS b 
WHERE a.postno = b.postno;

SELECT a.CONTENT, COUNT(b.postno) 
FROM POST a, COMMENTS b 
WHERE a.postno = b.postno(+);            


SELECT * FROM POST,comments;

SELECT location, hashtag, (SELECT count(*) 
                           FROM COMMENTS 
                           WHERE POSTNO = 14) cnt 
FROM POST ;



