/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2022-04-07 06:42:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.feed;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(11);
    _jspx_dependants.put("/WEB-INF/views/feed/../feed/modal2.jsp", Long.valueOf(1649297125547L));
    _jspx_dependants.put("jar:file:/D:/project_init/apache-tomcat-9.0.56/wtpwebapps/project_init/WEB-INF/lib/jstl-1.2.jar!/META-INF/sql.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-4.2.13.RELEASE.jar", Long.valueOf(1646873798857L));
    _jspx_dependants.put("jar:file:/D:/project_init/apache-tomcat-9.0.56/wtpwebapps/project_init/WEB-INF/lib/jstl-1.2.jar!/META-INF/x.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/feed/../header.jsp", Long.valueOf(1649049305126L));
    _jspx_dependants.put("/WEB-INF/views/feed/../footer.jsp", Long.valueOf(1647391121162L));
    _jspx_dependants.put("jar:file:/D:/project_init/apache-tomcat-9.0.56/wtpwebapps/project_init/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/project_init/apache-tomcat-9.0.56/wtpwebapps/project_init/WEB-INF/lib/spring-security-taglibs-4.2.13.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1560936316000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1644909417825L));
    _jspx_dependants.put("jar:file:/D:/project_init/apache-tomcat-9.0.56/wtpwebapps/project_init/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/project_init/apache-tomcat-9.0.56/wtpwebapps/project_init/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fauthorize_0026_005faccess;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005fauthorize_0026_005faccess = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005fauthorize_0026_005faccess.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write("   \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"_csrf\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta name=\"_csrf_header\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.headerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/b4e02812b5.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/feed/fc/main.js\"></script>\r\n");
      out.write("<script src=\"js/feed/fc/locales/ko.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/feed/feed_calendar.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- KAKAO API -->\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=94ef81dc370b9f961476a1859364f709&libraries=services\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"css/feed/fc/main.css\" rel=\"stylesheet\"></link>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/header.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/feed/main_custom.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/footer.css\" />\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write("   \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar navbar-default fixed-top border-bottom pt-3 bg-white\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"navbar-header\">\r\n");
      out.write("			<a href=\"/init\" class=\"navbar-brand\">\r\n");
      out.write("				<i class=\"menu-icon fa-solid fa-house\"></i>\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div>\r\n");
      out.write("			<div class=\"input-group border rounded bg-light\">\r\n");
      out.write("		    	<div class=\"input-group-btn\">\r\n");
      out.write("		    		<button type=\"button\" class=\"btn btn-default mr-1\">filter</button>\r\n");
      out.write("		        	<button type=\"button\" class=\"btn btn-default dropdown-toggle mr-1\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\"><span class=\"caret\"></span></button>\r\n");
      out.write("		        	<ul class=\"dropdown-menu\">\r\n");
      out.write("		          		<li>filter 1</li>\r\n");
      out.write("		          		<li>filter 2</li>\r\n");
      out.write("		          		<li>filter 3</li>\r\n");
      out.write("		        	</ul>\r\n");
      out.write("		      	</div>\r\n");
      out.write("		      	<input type=\"text\" class=\"form-control bg-light mr-1\" size=\"30\" aria-label=\"000\" placeholder=\"search...\">\r\n");
      out.write("	    		<a href=\"search\" class=\"btn btn-default mr-1\"><i class=\"fa-brands fa-sistrix\"></i></a>	      	\r\n");
      out.write("		    </div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<ul class=\"nav navbar\">\r\n");
      out.write("			");
      if (_jspx_meth_s_005fauthorize_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			");
      if (_jspx_meth_s_005fauthorize_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			<li class=\"mr-4 notice\">\r\n");
      out.write("				<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("					<i class=\"menu-icon fa-regular fa-bell\"></i>\r\n");
      out.write("				</a>\r\n");
      out.write("	        	<ul class=\"dropdown-menu\">\r\n");
      out.write("	        		");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	        	</ul>\r\n");
      out.write("				\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			<li class=\"mr-4 msg\">\r\n");
      out.write("				<a href=\"#\">\r\n");
      out.write("					<i class=\"menu-icon fa-regular fa-comment-dots\"></i>\r\n");
      out.write("				</a>\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		\r\n");
      out.write("	</div>		\r\n");
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("	$('#anFeed').click(function(e){\r\n");
      out.write("		e.preventDefault();\r\n");
      out.write("		$('#loginModalBtn').trigger('click');\r\n");
      out.write("	});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"container mb-5\">\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<div class=\"body-container\">\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		<div id=\"feed-header\" class=\"d-flex justify-content-start border-bottom row mx-0 flex-nowrap\">\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("			<div id=\"profile-left\" class=\"p-3 mb-5 bg-body col-5\"></div>\r\n");
      out.write("			\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("			<div id=\"profile-img\" class=\"p-3 mb-5 bg-body col-2 text-center\">\r\n");
      out.write("				<i class=\"profile-img fa-regular fa-circle-user\"></i>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("			<div id=\"profile-right\" class=\"p-3 mb-5 bg-body col-5\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		");
      out.write("		\r\n");
      out.write("		<ul class=\"feed-tabs row mx-0 flex-nowrap\">\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("			<li id=\"feed-calendar\" class='nav-item active col-3' data-tab=''>\r\n");
      out.write("				<a href=\"feed\" class=\"nav-link\">\r\n");
      out.write("					<i class=\"fa-regular fa-calendar-check\"></i>\r\n");
      out.write("				</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("			<li id=\"feed-map\" class='nav-item col-3' data-tab=''>\r\n");
      out.write("				<a href=\"feed/feedMap\" class=\"nav-link\">\r\n");
      out.write("					<i class=\"fa-solid fa-map-location-dot\"></i>\r\n");
      out.write("				</a>\r\n");
      out.write("			</li>\r\n");
      out.write("		\r\n");
      out.write("			");
      out.write("			\r\n");
      out.write("			<li id=\"feed-post\" class='nav-item col-3' data-tab=''>\r\n");
      out.write("				<a href=\"feed/feedPost\" class=\"nav-link\">\r\n");
      out.write("					<i class=\"fa-solid fa-images\"></i>\r\n");
      out.write("				</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			");
      out.write("			\r\n");
      out.write("			<li id=\"feed-info\" class='nav-item col-3' data-tab=''>\r\n");
      out.write("				<a href=\"feed/feedInfo\" class=\"nav-link\">\r\n");
      out.write("					<i class=\"fa-solid fa-gear\"></i>\r\n");
      out.write("				</a>\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		<div class=\"d-flex justify-content-between mt-5\" id=\"main-body\">\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("			<div class=\"border rounded p-3\">\r\n");
      out.write("				<form action=\"plan\" id=\"frm\" method=\"post\">\r\n");
      out.write("					");
      out.write("			\r\n");
      out.write("					<input type=\"hidden\" name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\r\n");
      out.write("					");
      out.write("	\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label for=\"planName\">일정 이름</label>\r\n");
      out.write("						<input type=\"text\" name=\"planName\" id=\"planName\" class=\"form-control\" required/>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					");
      out.write("	\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label for=\"startDate\">시작 일자</label>\r\n");
      out.write("						<input type=\"text\" name=\"startDate\" id=\"startDate\" class=\"form-control bg-light\" required readonly/>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					");
      out.write("	\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label for=\"endDate\">종료 일자</label>\r\n");
      out.write("						<input type=\"text\" name=\"endDate\" id=\"endDate\" class=\"form-control bg-light\" required readonly/>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					");
      out.write("	\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label for=\"eventColor\">블럭 색상</label>\r\n");
      out.write("						<select class=\"custom-select my-1 mr-sm-2 \" id=\"eventColor\" name=\"eventColor\">\r\n");
      out.write("							<option value=\"#007bff\" selected>Blue</option>\r\n");
      out.write("							<option value=\"#6610f2\">Indigo</option>\r\n");
      out.write("							<option value=\"#6f42c1\">Purple</option>\r\n");
      out.write("							<option value=\"#e83e8c\">Pink</option>\r\n");
      out.write("							<option value=\"#dc3545\">Red</option>\r\n");
      out.write("							<option value=\"#fd7e14\">Orange</option>\r\n");
      out.write("							<option value=\"#ffc107\">Yellow</option>\r\n");
      out.write("							<option value=\"#28a745\">Green</option>\r\n");
      out.write("							<option value=\"#20c997\">Teal</option>\r\n");
      out.write("							<option value=\"#17a2b8\">Cyan</option>\r\n");
      out.write("							<option value=\"#6c757d\">Gray</option>\r\n");
      out.write("							<option value=\"gray-dark\">Dark Gray</option>\r\n");
      out.write("						</select>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					");
      out.write("	\r\n");
      out.write("					<input type=\"hidden\" name=\"dateCount\" id=\"dateCount\" class=\"form-control\"/>\r\n");
      out.write("					\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("					<div class=\"d-flex justify-content-end mp_btn\">\r\n");
      out.write("						<button type=\"submit\" class=\"btn btn-sm btn-primary mr-1\" id=\"submit\" >Create</button>\r\n");
      out.write("						<input type=\"reset\" class=\"btn btn-sm btn-danger px-2\" id=\"reset\" value=\"Clear\" />\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("			<div id=\"calendar\"></div>\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("			<input type=\"hidden\" id=\"modalBtn\" data-toggle=\"modal\" data-target=\"#detailModal\" value=\"modal\" />\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=92b6b7355eb56122be94594a5e40e5fd\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<div class=\"modal fade\" id=\"detailModal\" role=\"dialog\">\r\n");
      out.write("		<div class=\"modal-dialog modal-dialog-centered modal-xl d-block\">\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("			<button type=\"button\" id=\"modalCloseBtn\" class=\"btn btn-sm btn-default text-white text-weight-bold display-1 float-right\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("				<div class=\"modal-header bg-light d-flex justify-content-start\">\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("					<h4 id=\"plan-name\" class=\"modal-title display-4 font-italic\"></h4>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("				<div class=\"modal-body bg-light\">\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("					<form action=\"#\" class=\"row\" method=\"post\" id=\"modify_form\">\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("						<input type=\"hidden\" name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("						<input type=\"hidden\" name=\"planNum\" id=\"modal-planNum\" />\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("						<input type=\"hidden\" name=\"originDateCount\" id=\"modal-originDateCount\" value=\"\" />\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("						<input type=\"hidden\" name=\"newDateCount\" id=\"modal-newDateCount\" value=\"\" />\r\n");
      out.write("						\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("						<div class=\"form-group col-8\">\r\n");
      out.write("							<label for=\"planName\">일정 이름</label>\r\n");
      out.write("							<input type=\"text\" id=\"modal-planName\" name=\"planName\" class=\"form-control\"/>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("						<div class=\"form-group col-4\">\r\n");
      out.write("							<label for=\"modal-eventColor\">블럭 색상</label>\r\n");
      out.write("							<select class=\"custom-select my-1 mr-sm-2 \" id=\"modal-eventColor\" name=\"eventColor\">\r\n");
      out.write("								<option value=\"#007bff\" selected>Blue</option>\r\n");
      out.write("								<option value=\"#6610f2\">Indigo</option>\r\n");
      out.write("								<option value=\"#6f42c1\">Purple</option>\r\n");
      out.write("								<option value=\"#e83e8c\">Pink</option>\r\n");
      out.write("								<option value=\"#dc3545\">Red</option>\r\n");
      out.write("								<option value=\"#fd7e14\">Orange</option>\r\n");
      out.write("								<option value=\"#ffc107\">Yellow</option>\r\n");
      out.write("								<option value=\"#28a745\">Green</option>\r\n");
      out.write("								<option value=\"#20c997\">Teal</option>\r\n");
      out.write("								<option value=\"#17a2b8\">Cyan</option>\r\n");
      out.write("								<option value=\"#6c757d\">Gray</option>\r\n");
      out.write("								<option value=\"gray-dark\">Dark Gray</option>\r\n");
      out.write("							</select>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("						<div class=\"form-group col-6\">\r\n");
      out.write("							<label for=\"modal-startDate\">시작 일자</label>\r\n");
      out.write("							<input type=\"date\" id=\"modal-startDate\" name=\"startDate\" class=\"form-control\"/>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("						<div class=\"form-group col-6\">\r\n");
      out.write("							<label for=\"modal-endDate\">종료 일자</label>\r\n");
      out.write("							<input type=\"date\" id=\"modal-endDate\" name=\"endDate\" class=\"form-control\"/>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("					\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("					<div class=\"button-group d-flex justify-content-end mt-2\">\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("						<button type=\"submit\" id=\"btn-modify\" class=\"btn btn-sm btn-success mx-1\">일정 수정</button>\r\n");
      out.write("						\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("						<button type=\"button\" id=\"btn-delete\" class=\"btn btn-sm btn-danger mx-1\">일정 삭제</button>\r\n");
      out.write("						\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("						<a href=\"\" id=\"btn-detail\" class=\"btn btn-sm btn-dark mx-1\">상세 수정</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("					<div class=\"detail-days d-flex\" data-count=\"\">\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-outline-default text-dark col-1\" id=\"prev-btn\" data-index=\"0\">\r\n");
      out.write("							<i class=\"fa-solid fa-angle-left\"></i>\r\n");
      out.write("						</button>\r\n");
      out.write("						\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("						<h4 id=\"plan-day\" class=\"display-4 font-italic\"></h4>\r\n");
      out.write("						\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-outline-default text-dark col-1\" id=\"next-btn\" data-index=\"2\">\r\n");
      out.write("							<i class=\"fa-solid fa-angle-right\"></i>\r\n");
      out.write("						</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("					<div class=\"plan-details mt-2 d-flex row mx-0\">\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("						<div id=\"map\" class=\"col-8 border\"></div>\r\n");
      out.write("						\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("						<div id=\"details1\" class=\"col-4 px-0\">\r\n");
      out.write("							");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			<div class=\"modal-footer bg-light mb-2\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write("   \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer class=\"bg-dark\">\r\n");
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("// feed tab 메뉴 각각의 요소 클릭했을 때,\r\n");
      out.write("$('.nav-link').click(function(e) {\r\n");
      out.write("	// feed일 때는 feed 페이지로 재진입, 아닐때는 get방식 ajax호출해서 #main-body에 html 뿌림\r\n");
      out.write("	if ( $(this).attr('href') != 'feed' ) {\r\n");
      out.write("		e.preventDefault();\r\n");
      out.write("		\r\n");
      out.write("		// 현재 active로 되어있는 tab menu의 active 클래스를 삭제\r\n");
      out.write("		$(this).parent().siblings('.active').removeClass('active');\r\n");
      out.write("		\r\n");
      out.write("		// 클릭된 요소에 active 클래스 부여\r\n");
      out.write("		$(this).parent().addClass('active');\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		// 해당되는 페이지 jsp 파일을 #main-body에 뿌려주는 ajax\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url: $(this).attr('href'),\r\n");
      out.write("			type: 'get',\r\n");
      out.write("			success: function(data) {\r\n");
      out.write("				// post에서 더보기 버튼으로 늘어났을 때, main-body의 height를 초기화\r\n");
      out.write("				var height = $('#main-body').height(1000);\r\n");
      out.write("				\r\n");
      out.write("				if ( Number(height) > 1000 ) {\r\n");
      out.write("					$('#main-body').height(1000);\r\n");
      out.write("				};\r\n");
      out.write("				\r\n");
      out.write("				$('#main-body').html(data);\r\n");
      out.write("				\r\n");
      out.write("			},\r\n");
      out.write("			error: function(data) {\r\n");
      out.write("				console.log(data);\r\n");
      out.write("				alert('ajax 실패');\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("	}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005fauthorize_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_s_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fs_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_s_005fauthorize_005f0_reused = false;
    try {
      _jspx_th_s_005fauthorize_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fauthorize_005f0.setParent(null);
      // /WEB-INF/views/feed/../header.jsp(46,3) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fauthorize_005f0.setAccess("isAnonymous()");
      int _jspx_eval_s_005fauthorize_005f0 = _jspx_th_s_005fauthorize_005f0.doStartTag();
      if (_jspx_eval_s_005fauthorize_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("				<li class=\"mr-4 feed\">\r\n");
        out.write("					<a href=\"feed\" id=\"anFeed\">\r\n");
        out.write("						<i class=\"menu-icon fa-regular fa-circle-user\"></i>\r\n");
        out.write("					</a>\r\n");
        out.write("				</li>\r\n");
        out.write("			");
      }
      if (_jspx_th_s_005fauthorize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fauthorize_0026_005faccess.reuse(_jspx_th_s_005fauthorize_005f0);
      _jspx_th_s_005fauthorize_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fauthorize_005f0, _jsp_getInstanceManager(), _jspx_th_s_005fauthorize_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fauthorize_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_s_005fauthorize_005f1 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fs_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_s_005fauthorize_005f1_reused = false;
    try {
      _jspx_th_s_005fauthorize_005f1.setPageContext(_jspx_page_context);
      _jspx_th_s_005fauthorize_005f1.setParent(null);
      // /WEB-INF/views/feed/../header.jsp(54,3) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fauthorize_005f1.setAccess("isAuthenticated()");
      int _jspx_eval_s_005fauthorize_005f1 = _jspx_th_s_005fauthorize_005f1.doStartTag();
      if (_jspx_eval_s_005fauthorize_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("				<li class=\"mr-4 feed\">\r\n");
        out.write("					<a href=\"feed\" id=\"loginFeed\">\r\n");
        out.write("						<i class=\"menu-icon fa-regular fa-circle-user\"></i>\r\n");
        out.write("					</a>\r\n");
        out.write("				</li>\r\n");
        out.write("			");
      }
      if (_jspx_th_s_005fauthorize_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fauthorize_0026_005faccess.reuse(_jspx_th_s_005fauthorize_005f1);
      _jspx_th_s_005fauthorize_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fauthorize_005f1, _jsp_getInstanceManager(), _jspx_th_s_005fauthorize_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/feed/../header.jsp(66,11) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setBegin(1);
      // /WEB-INF/views/feed/../header.jsp(66,11) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setEnd(10);
      // /WEB-INF/views/feed/../header.jsp(66,11) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("i");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("			          	<li class=\"list-group-item\">\r\n");
            out.write("			          		alarm");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("			          	</li>\r\n");
            out.write("		          	");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/feed/../feed/modal2.jsp(113,7) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setBegin(1);
      // /WEB-INF/views/feed/../feed/modal2.jsp(113,7) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setEnd(10);
      // /WEB-INF/views/feed/../feed/modal2.jsp(113,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("i");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("								<div class=\"list-group-item planDt");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" flex-row mx-0 px-1 pt-2\">\r\n");
            out.write("									<h4 class=\"placeName col-12 font-italic\"></h4>\r\n");
            out.write("									<h6 class=\"font-italic col-6 startTime\"></h6>\r\n");
            out.write("									<h6 class=\"font-italic col-6 endTime\"></h6>\r\n");
            out.write("								</div>\r\n");
            out.write("							");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
